#!/bin/bash
 
REMOTE=turkotron@91.121.7.111
REMOTE_APP=/home/turkotron/
 
sbt stage || exit 1;
rsync -va target/ $REMOTE:$REMOTE_APP/target;
ssh $REMOTE "cd $REMOTE_APP; ./stop.sh";
ssh $REMOTE "cd $REMOTE_APP; ./start.sh";
